# Generated by Django 4.2 on 2024-10-16 15:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Node",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("operator", "Operator"), ("operand", "Operand")],
                        max_length=10,
                    ),
                ),
                ("value", models.TextField(blank=True, null=True)),
                (
                    "left",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="left_child",
                        to="rules.node",
                    ),
                ),
                (
                    "right",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="right_child",
                        to="rules.node",
                    ),
                ),
            ],
        ),
    ]
